### ISSUE TITLE
Undefined symbols

### ISSUE THREAD

**Issue by Pickles112358** [blinkinput/blinkinput-ios#17]
If there is a compile error similar to this:

```
ignoring file ../../MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): ../../MicroBlink.framework/MicroBlink
Undefined symbols for architecture arm64:
```

It probably means that Git LFS was not correctly installed. To be sure, you can check the file size of your local MicroBlink file (located in MicroBlink.framework). The size should be around 100MB, while the size of incorrectly downloaded file would be less than 1KB.

To fix this issues you can:
- Follow our ["Getting Started" guide](https://github.com/BlinkOCR/blinkocr-ios/wiki/Getting-started) and pay close attention to parts related to Git LFS while installing our SDK

OR
- [Download BlinkOCR SDK](https://github.com/BlinkOCR/blinkocr-ios/releases) manually. Download .zip or .tar.gz file starting with BlinkOCR. DO NOT download Source Code as GitHub does not fully support Git Large File Storage

**Comment by imizaac** [comment]
Literally half of the issues are this problem...
