### ISSUE TITLE
Landscape mode Problem Using Blink OCR(IOS)

### ISSUE THREAD

**Issue by Kumar673** [blinkinput/blinkinput-ios#22]
I integrated Blink OCR SDK in my project, But it is working fine with 80% accuracy for Portrait mode, But
 When scan the passport document, I got some Results in undefined data in landscape mode(Totally wrong data).

![img_2191](https://cloud.githubusercontent.com/assets/25683512/22821527/85d8cfa8-efa1-11e6-89e1-292219e0c321.PNG)
![img_2192](https://cloud.githubusercontent.com/assets/25683512/22821557/a5a1425c-efa1-11e6-9af8-148b368677c2.PNG)

**Comment by culoi** [comment]
Hello @Kumar673 

Can you please describe me what are you trying to scan in passport? 

Are you trying to extract specific data?
