### ISSUE TITLE
Arm64 architecture missing

### ISSUE THREAD

**Issue by ratnesh-iOSdev** [blinkinput/blinkinput-ios#23]
<img width="865" alt="screen shot 2017-04-04 at 12 08 29 am" src="https://cloud.githubusercontent.com/assets/8231338/24624944/fddfef8e-18ca-11e7-866b-49f267314fa8.png">

**Comment by bryanbartow** [comment]
Getting the same error(s). Is there a fix for this:

**Comment by culoi** [comment]
Hello,

Did you use git-lfs as described in documentation here: https://github.com/blinkinput/blinkinput-ios/blob/master/README.md#integration-without-cocoapods

Regards

**Comment by bryanbartow** [comment]
I downloaded the zip file.

**Comment by ucdrstdenis** [comment]
You're best bet is to install it manually. Download the framework, add it to your project, add the necessary libraries into your project file like so:

![screen shot 2018-07-19 at 11 01 27 pm](https://user-images.githubusercontent.com/8234564/42980983-d3981cc8-8ba7-11e8-9ad1-c0957816ed9b.png)

**Comment by bryanbartow** [comment]
Already done:
<img width="865" alt="screen shot 2018-07-20 at 1 33 53 pm" src="https://user-images.githubusercontent.com/867678/43019238-e9444716-8c21-11e8-9cbf-7877023660cc.png">
