### ISSUE TITLE
Cannot run the sample code

### ISSUE THREAD

**Issue by nachiketdesai** [blinkinput/blinkinput-ios#24]
When I try and run the sample code, I get the following error

BlinkInputTest[3507:2042538] *** Assertion failure in -[PPResourceManager loadZicerModel], /Users/dino/MicroBlink/Workspace/BlinkOCR/blinkocr-ios-demo/blinkocr-ios-framework/core-ios/CommonFramework/Services/PPResourceManager.mm:214
2017-04-05 13:45:42.174168 BlinkInputTest[3507:2042538] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Zicer model must not be null!'

**Comment by culoi** [comment]
Hello @nachiketdesai 

It looks like that MicroBlink.bundle is not included in your app. 
My advice would be to read through our "Getting Started guide" available here:
https://github.com/BlinkOCR/blinkocr-ios/wiki/Getting-started

If you follow the steps correctly your app should work without a problem.

Please let me know if this works for you? 

Regards,

Ivan
