### ISSUE TITLE
-ld build error again with Cocoapods

### ISSUE THREAD

**Issue by XyrisKennEnrian** [blinkinput/blinkinput-ios#31]
Hello, 

The ld linker file related to git lfs is appearing again in my Cocopods build after updating to PPBlinkID version 2.12 in Xcode 9 and OSX 10.13 (High Sierra):

ld: warning: ignoring file /Users/[redacted]/iOS Dev/[redacted]/[redacted]/Pods/PPBlinkID/MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/[redacted]/iOS Dev/[redacted]/[redacted]/Pods/PPBlinkID/MicroBlink.framework/MicroBlink

I've installed brew and lfs support onto a fresh install of OSX High Sierra, removed Derived Data, removed and re-installed Pods, restarted Terminal and the computer, performed git lfs pull in the project and in the pod directory, but BlinkID still will not build correctly from Cocoapods.

What might you recommend as a solution?

**Comment by imizaac** [comment]
In the past the resolution to this issue has often been to ensure that git-lfs is working, which tends to fix the problem.

**Comment by culoi** [comment]
Hello @XyrisKennEnrian 

You can also check out our Zendesk support article: https://microblink.zendesk.com/hc/en-us/articles/115005241205-iOS-linker-command-failed-with-exit-code-1

Please let me know how it works for you.

Regards,

Ivan
