### ISSUE TITLE
Capture Image with PPOverlayViewController

### ISSUE THREAD

**Issue by yagneshGingercube** [blinkinput/blinkinput-ios#32]
Hi, 
I am working on prototype with BlinkInput SDK(OCR) to scan text . I am using  **PPOverlayViewController** to customize camera. But I am not able capture image with BlinkInput SDK after scanning text . Earlier we had method called **getPreviewLayer** in **PPOverlayContainerViewController** interface. Now I don't see it . Is it deprecated ? Is there any alternative solution available to capture image ?

Please reply 

**Note** : I am working iOS app . I have installed **BlinkInput** without using CocoaPods. Text scanning feature is working fine. 
Thanks

**Comment by cularj** [comment]
Hi @yagneshGingercube ,

First you will need to set `currentFrame` property in your PPSettings instance to `YES`:

`settings.metadataSettings.currentFrame = YES;`

in your `PPScanningDelegate` you can implement `-(void)scanningViewController:didOutputMetadata:` method. It will be invoked every time SDK captures a frame, so you can save the latest image you receive, something like this.

```Objective-c
- (void)scanningViewController:(UIViewController<PPScanningViewController> *)scanningViewController
             didOutputMetadata:(PPMetadata *)metadata {

    // Check if metadata obtained is image. You can set what type of image is outputed by setting different properties of PPMetadataSettings
    if ([metadata isKindOfClass:[PPImageMetadata class]]) {
        PPImageMetadata *imageMetadata = (PPImageMetadata *)metadata;

        if (imageMetadata.imageType == PPImageMetadataTypeCurrentFrame) {
            self.currentFrame = imageMetadata.image;
        }
    }
}

```

Kind regards,
Jure
