### ISSUE TITLE
PPDocumentClassifier for PPDecectorRecognizer

### ISSUE THREAD

**Issue by imizaac** [blinkinput/blinkinput-ios#33]
Hey guys

I have just upgraded from 2.2.0 to 2.3.0. Previously I was using a PPBlinkOcrRecognizer and PPBlinkOcrSettings to do template analysis as instructed by the 2.2.0 sample code.

In my transition I switched to using a PPDetectorRecognizer, as the 2.3.0 Templating-Sample does. I would be able to parse results fine if was only processing one document, but I cannot find a way to set my classifier. As a result my classifier is never called and I cannot classify results.

I'm sure its in there somewhere, but I can't find it. 

I also cannot find any calls to set it in the Templating-Sample, so there is a possibility it is not a working sample.

**Comment by cularj** [comment]
Hi @imizaac, 

this is a bug we will fix in the next release, in the meantime we suggest using the PPBlinkOcrRecognizer.

Kind regards,
Jure

**Comment by madhuchprimekeeper** [comment]
Hi Jure,

I also facing same issue when can we expect next release.Actually we are waiting for the release.

**Comment by madhuchprimekeeper** [comment]
Hi Jure,

I updated to PPBlinkID for 2.14.0 still I cannot find a way to set my classifier. As a result my classifier is never called and I cannot classify results.

**Comment by madhuchprimekeeper** [comment]
Hi jure,

I updated BlinkOcr 2.14.0 still  I cannot find a way to set my classifier. As a result my classifier is never called and I cannot classify results.

**Comment by cularj** [comment]
Hi @madhuchprimekeeper 

next release of BlinkID will be before Christmas in which the fix for this issue will be included.

Kind regards,
Jure

**Comment by culoi** [comment]
Hello @imizaac @madhuchprimekeeper 

Do you still need assistance on this topic? 

Regards
