### ISSUE TITLE
BlinkInput-ios for react-native

### ISSUE THREAD

**Issue by jojoucsd** [blinkinput/blinkinput-ios#34]
Hi, I am currently working with blinkID-react-native on my project. I would also like to add BlinkInput to my react-native projects. Is there any easier way I can add the feature in or following the iOS step is my solution? Thanks very much!

**Comment by jcular** [comment]
If you want to use raw ocr or parsers from blinkinput, implementing them natively and wrapping them as native-modules is probably the easiest way.
I'll close this issue since blinkid-react-native has changed and if you need help open another issue.

Kind regards,
Jure
