### ISSUE TITLE
Cannot build the Sample codes.

### ISSUE THREAD

**Issue by MasaruKitajima** [blinkinput/blinkinput-ios#35]
I've downloaded the ZIP from this repo. And tried to build BlinkOCR-sample, but it failed.

The erros I got is as following screen shot.

How can I solve this?

<img width="567" alt="xcode001" src="https://user-images.githubusercontent.com/3312530/33199963-f066039c-d135-11e7-90b2-513d64c9b934.png">

**Comment by culoi** [comment]
Hello @MasaruKitajima

Did you follow our instruction as specified in our readme file:
https://github.com/blinkinput/blinkinput-ios/blob/master/README.md#installation-with-cocoapods

Mach-O linker error indicates issues with Git-lfs, so please make sure that you have it installed via brew.

Please let me know how this works for you.

Regards,

Ivan

**Comment by MasaruKitajima** [comment]
Thank you so much.

And I'm so sorry to be late in writing you back. I've had a high fever and stayed in bed.
The sample succeded to compile.

Does this mean if I want to create my own app, I need to use git-lfs?

**Comment by culoi** [comment]
Hi @MasaruKitajima 

You have to use git-lfs to fetch all necessary files for our SDK.
During the building of your app, there is no need as we use Git-lfs only for storing large files.

Here you can find more info about Git-lfs: https://git-lfs.github.com/

Regards

**Comment by EugeneGordin2303** [comment]
Hi @culoi I'm having same issues. I did install git-lfs by running brew. Still seeing the issues while trying to compile your sample app.

**Comment by culoi** [comment]
@EugeneGordin2303 

Is the issue still present? Can you share which version of the brew and git-lfs are you using?

Regards
