### ISSUE TITLE
unable to integrate with pod

### ISSUE THREAD

**Issue by anupgupta-arg** [blinkinput/blinkinput-ios#36]
Hi,
I am trying to integrate the MicroBlink into our project but I am getting the error every time.
I try 2 different method
**Method 1:**
I tried with direct to import MicroBlink framework in our project 
**result:** now working error

**Method 2:** 
using pod I integrate the pod but I am getting the same error

![screen shot 2017-12-08 at 10 57 34 am](https://user-images.githubusercontent.com/6472263/33754642-330751c8-dc13-11e7-931b-3ccc859a351a.png)
**HOW to reslove this issue????**

**Comment by anupgupta-arg** [comment]
Hi, 
![screen shot 2017-12-08 at 12 41 18 pm](https://user-images.githubusercontent.com/6472263/33755066-29454c38-dc15-11e7-919e-5d5e343d9cb6.png)
this is my pod file.

**Comment by culoi** [comment]
Hello @anupgupta-arg 

Linker error usually indicates [Git-lfs](https://git-lfs.github.com/) issue. 

Please make sure that you have git-lfs installed via brew:
`brew install git-lfs`
`git lfs install`

Don't forget to restart the terminal.

Here is the similar issue on our support channel for the BlinkID: https://microblink.zendesk.com/hc/en-us/articles/115005241205-iOS-linker-command-failed-with-exit-code-1
but you can follow the same procedure for the BlinkInput.

Also please follow integration with [the pods](https://github.com/blinkinput/blinkinput-ios/wiki/Getting-started#using-cocoapods) and [without pods](https://github.com/blinkinput/blinkinput-ios/wiki/Getting-started#integration-without-cocoapods)

Please let me know how it works.

Regards,

Ivan

**Comment by anupgupta-arg** [comment]
Hello @culoi 

Thank you, now its working.

Regards, 
Anup
